const $=(s)=>document.querySelector(s)
const viewport=$('.viewport'),seed=$('#seed')
const overlay=document.createElement('canvas');overlay.id='living-city-canvas';overlay.setAttribute('aria-label','3D 교통·시설 시뮬레이션 오버레이');viewport.appendChild(overlay)
const info=document.createElement('aside');info.id='object-inspector';info.className='object-inspector';info.innerHTML='<div class="inspector-head"><strong>도시 객체</strong><button type="button" aria-label="닫기">×</button></div><div id="inspector-body">차량·역·시설을 선택하세요.</div>';viewport.appendChild(info);info.querySelector('button').addEventListener('click',()=>info.classList.remove('open'))
const state={agents:[],pois:[],heat:[],flood:[],selected:null}
function hash(t){let h=2166136261;for(const c of t){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rngFactory(v){let s=hash(v);return()=>((s=Math.imul(s,1664525)+1013904223>>>0)/4294967296)}
function reset(){const r=rngFactory(seed?.value||'city');state.agents=[];state.pois=[];state.heat=[];state.flood=[];for(let i=0;i<62;i++){const n=r();state.agents.push({id:`T-${i+1}`,type:i%17===0?'train':i%8===0?'bus':i%13===0?'truck':'car',axis:i%2,x:r(),y:r(),speed:.018+r()*.045,dir:r()>.5?1:-1,lane:r(),tone:n})}const types=['학교','병원','소방서','경찰서','환승센터','공원'];for(let i=0;i<18;i++)state.pois.push({id:`P-${i+1}`,x:.08+r()*.84,y:.12+r()*.76,type:types[i%types.length],capacity:Math.round(80+r()*920),score:Math.round(62+r()*37)});for(let y=0;y<10;y++)for(let x=0;x<14;x++){const center=Math.hypot(x/13-.5,y/9-.48);state.heat.push({x,y,v:Math.max(0,1-center*1.7+r()*.35)});state.flood.push({x,y,v:Math.max(0,(y/9)*.45+r()*.5-(x/13-.72)**2)})}}
function resize(){const d=Math.min(devicePixelRatio||1,2),w=viewport.clientWidth,h=viewport.clientHeight;overlay.width=w*d;overlay.height=h*d;overlay.style.width=`${w}px`;overlay.style.height=`${h}px`;overlay.getContext('2d').setTransform(d,0,0,d,0,0)}
function analysis(){return document.querySelector('[data-analysis].active')?.dataset.analysis||'none'}
function project(nx,ny,w,h){const horizon=h*.27,bottom=h*.96,depth=.16+ny*.84,halfTop=w*.27,halfBottom=w*.58,half=halfTop+(halfBottom-halfTop)*depth;return{x:w*.5+(nx-.5)*half*2,y:horizon+(bottom-horizon)*Math.pow(depth,.88),scale:.34+depth*.92}}
function roadPoint(a,t,w,h){let nx,ny;if(a.axis===0){nx=(a.x+t*a.speed*a.dir+20)%1;ny=.08+Math.round(a.y*8)/8*.84}else{nx=.07+Math.round(a.x*10)/10*.86;ny=(a.y+t*a.speed*a.dir+20)%1}const p=project(nx,ny,w,h);return{...p,angle:a.axis===0?0:Math.PI/2,agent:a}}
function drawGrid(ctx,w,h,kind){const cells=kind==='heat'?state.heat:state.flood;for(const c of cells){const p1=project(c.x/14,c.y/10,w,h),p2=project((c.x+1)/14,(c.y+1)/10,w,h),a=Math.min(.34,c.v*.34);ctx.fillStyle=kind==='heat'?`rgba(255,82,42,${a})`:`rgba(45,146,255,${a})`;ctx.fillRect(p1.x,p1.y,p2.x-p1.x+2,p2.y-p1.y+2)}}
function poly(ctx,pts,fill){ctx.fillStyle=fill;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill()}
function drawVehicle(ctx,p){const a=p.agent,s=p.scale,train=a.type==='train',bus=a.type==='bus',truck=a.type==='truck',L=(train?25:bus?15:truck?12:8)*s,W=(train?5.2:bus?4.8:truck?4.4:3.7)*s,H=(train?4.2:bus?4.8:truck?4.2:2.8)*s;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle+(a.dir<0?Math.PI:0));ctx.globalAlpha=.94;ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,H*.58,L*.54,W*.72,0,0,Math.PI*2);ctx.fill();const body=train?'#5fc9e9':bus?'#e7b44c':truck?'#b96d55':a.tone>.66?'#d5dce0':a.tone>.33?'#467da0':'#b95b52';poly(ctx,[[-L/2,0],[L/2,0],[L*.43,-H],[ -L*.38,-H]],body);poly(ctx,[[-L*.38,-H],[L*.43,-H],[L*.29,-H-W*.56],[-L*.24,-H-W*.56]],train?'#9ee9f6':'#dfe9ec');poly(ctx,[[L/2,0],[L*.43,-H],[L*.29,-H-W*.56],[L*.52,-W*.18]],train?'#2788a8':'#26343c');ctx.fillStyle='rgba(174,224,240,.82)';const windows=train?5:bus?4:truck?1:2;for(let i=0;i<windows;i++){const x=-L*.27+i*(L*.54/Math.max(1,windows-1));ctx.fillRect(x,-H*.82,L*.10,H*.28)}ctx.fillStyle='#1b2329';for(const x of[-L*.28,L*.28]){ctx.beginPath();ctx.arc(x,W*.1,W*.18,0,Math.PI*2);ctx.fill()}if(train){ctx.strokeStyle='#8fe4ff';ctx.lineWidth=Math.max(1,s*1.3);ctx.beginPath();ctx.moveTo(-L*.52,H*.15);ctx.lineTo(L*.52,H*.15);ctx.stroke()}ctx.restore()}
function poiIcon(type){return{학교:'S',병원:'H',소방서:'F',경찰서:'P',환승센터:'M',공원:'G'}[type]||'•'}
function drawPoi(ctx,p,w,h,mode){const q=project(p.x,p.y,w,h),r=6+q.scale*2;if(mode==='service'){ctx.strokeStyle='rgba(89,220,159,.22)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(q.x,q.y,18+p.score*.2*q.scale,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='rgba(9,23,32,.9)';ctx.strokeStyle='rgba(132,220,255,.9)';ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(q.x,q.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#d8f2fa';ctx.font=`700 ${Math.max(8,8*q.scale)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(poiIcon(p.type),q.x,q.y+.5);p._screen=q}
function draw(ts){const ctx=overlay.getContext('2d'),w=viewport.clientWidth,h=viewport.clientHeight;ctx.clearRect(0,0,w,h);const mode=analysis();if(mode==='heat'||mode==='flood')drawGrid(ctx,w,h,mode);const points=state.agents.map(a=>roadPoint(a,ts/1000,w,h)).sort((a,b)=>a.y-b.y);for(const p of points)drawVehicle(ctx,p);for(const p of state.pois)drawPoi(ctx,p,w,h,mode);requestAnimationFrame(draw)}
function nearest(x,y){let best=null,dist=30;for(const p of state.pois){if(!p._screen)continue;const d=Math.hypot(p._screen.x-x,p._screen.y-y);if(d<dist){dist=d;best=p}}return best}
overlay.addEventListener('pointerdown',e=>{const r=overlay.getBoundingClientRect(),p=nearest(e.clientX-r.left,e.clientY-r.top);if(!p)return;state.selected=p;info.classList.add('open');$('#inspector-body').innerHTML=`<dl><div><dt>객체 ID</dt><dd>${p.id}</dd></div><div><dt>유형</dt><dd>${p.type}</dd></div><div><dt>수용 규모</dt><dd>${p.capacity.toLocaleString('ko-KR')}명</dd></div><div><dt>서비스 점수</dt><dd>${p.score}/100</dd></div><div><dt>운영 상태</dt><dd>${p.score>80?'정상':'주의'}</dd></div></dl>`})
function expose(){window.ProceduralCitySimulation={reset,getSnapshot:()=>({agents:state.agents.length,facilities:state.pois.length,analysis:analysis(),renderer:'perspective-transport-v1'}),setAnalysis:m=>document.querySelector(`[data-analysis="${m}"]`)?.click()};window.dispatchEvent(new CustomEvent('procedural-city:simulation-ready',{detail:window.ProceduralCitySimulation}))}
window.addEventListener('resize',resize);$('#generate')?.addEventListener('click',()=>setTimeout(reset,320));$('#random-seed')?.addEventListener('click',()=>setTimeout(reset,160));resize();reset();expose();requestAnimationFrame(draw)
