const q=(s)=>document.querySelector(s)
const qa=(s)=>[...document.querySelectorAll(s)]
const viewport=q('.viewport')
const timeSlider=q('#time-of-day')
const timeLabel=q('#time-value')
const seedInput=q('#seed')
const sim={minutes:15*60,date:new Date(2040,6,31),running:true,speed:60,climate:'temperate',weather:'auto',currentWeather:'clear',season:'summer',analysis:'none',lastWeatherChange:0}
const climates={temperate:{temp:[2,9,22,12],rain:.24,snow:.12},continental:{temp:[-5,8,25,10],rain:.18,snow:.22},monsoon:{temp:[4,13,28,16],rain:.38,snow:.06},oceanic:{temp:[7,12,21,14],rain:.32,snow:.04},arid:{temp:[11,20,32,23],rain:.05,snow:0}}
const seasonIndex={winter:0,spring:1,summer:2,autumn:3}
function hash(v){let h=2166136261;for(const c of v){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(){sim._seed=(Math.imul(sim._seed||hash(seedInput?.value||'city'),1664525)+1013904223)>>>0;return sim._seed/4294967296}
function formatTime(){const h=Math.floor(sim.minutes/60)%24,m=Math.floor(sim.minutes%60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function seasonFromDate(){const m=sim.date.getMonth();return m<2||m===11?'winter':m<5?'spring':m<8?'summer':'autumn'}
function chooseWeather(){if(sim.weather!=='auto')return sim.weather;const c=climates[sim.climate];const r=rnd();if(sim.season==='winter'&&r<c.snow)return'snow';if(r<c.rain)return rnd()>.55?'rain':'overcast';if(r<c.rain+.13)return'fog';if(r>.86)return'overcast';return'clear'}
function temperature(){const c=climates[sim.climate],base=c.temp[seasonIndex[sim.season]],hour=sim.minutes/60,diurnal=Math.sin((hour-8)/24*Math.PI*2)*4,weatherPenalty={clear:1,overcast:-1,rain:-3,snow:-5,fog:-2}[sim.currentWeather]||0;return Math.round(base+diurnal+weatherPenalty)}
function weatherName(w){return{clear:'맑음',overcast:'흐림',rain:'비',snow:'눈',fog:'안개'}[w]||w}
function updateEnvironment(){sim.season=seasonFromDate();sim.currentWeather=chooseWeather();const hour=sim.minutes/60;viewport.classList.toggle('sim-night',hour<6.5||hour>19.5);viewport.classList.toggle('sim-dusk',(hour>=17.5&&hour<=20)||(hour>=5&&hour<7));viewport.classList.toggle('sim-overcast',['overcast','rain','snow','fog'].includes(sim.currentWeather));const layer=q('#weather-layer');layer.className=`weather-layer ${sim.currentWeather}`;layer.innerHTML='';if(['rain','snow'].includes(sim.currentWeather)){for(let i=0;i<72;i++){const p=document.createElement('i');p.className='weather-particle';p.style.left=`${rnd()*110}%`;p.style.animationDuration=`${sim.currentWeather==='rain'?.55+rnd()*.5:3+rnd()*4}s`;p.style.animationDelay=`-${rnd()*5}s`;p.style.opacity=.3+rnd()*.7;layer.appendChild(p)}}q('#env-weather').textContent=weatherName(sim.currentWeather);q('#env-temp').textContent=`${temperature()}°C`;q('#env-clock').textContent=formatTime();q('#env-date').textContent=`${sim.date.getMonth()+1}월 ${sim.date.getDate()}일`;q('#sim-event').textContent=eventText();if(timeSlider){timeSlider.value=hour;timeSlider.dispatchEvent(new Event('input',{bubbles:true}))}if(timeLabel)timeLabel.textContent=formatTime();updateKPIs()}
function eventText(){const pool={clear:['대중교통 운행 정상','도심 보행량 증가','태양광 발전량 양호'],overcast:['일사량 감소','도로 혼잡도 보통','공원 이용량 감소'],rain:['강우 배수망 가동','교량 감속 운행','대중교통 수요 증가'],snow:['제설 우선도로 가동','산지 도로 통제 검토','전력 피크 수요 상승'],fog:['가시거리 저하','교량 안전등 점등','항공·물류 지연 가능']}[sim.currentWeather];return pool[Math.floor(rnd()*pool.length)]}
function numeric(id){return Number((q(id)?.textContent||'0').replace(/[^0-9.]/g,''))||0}
function updateKPIs(){const pop=numeric('#metric-population'),jobs=numeric('#metric-jobs'),green=numeric('#metric-green'),transit=numeric('#metric-transit'),roads=numeric('#metric-roads');const temp=temperature();q('#kpi-pop').textContent=pop?Math.round(pop).toLocaleString('ko-KR'):'—';q('#kpi-jobs').textContent=jobs?Math.round(jobs).toLocaleString('ko-KR'):'—';q('#kpi-density').textContent=pop?`${Math.max(1200,Math.round(pop/Math.max(1,numeric('#grid-size-value')||30)))} /㎢`:'—';q('#kpi-green').textContent=`${green||0}%`;q('#kpi-transit').textContent=`${transit||0}%`;q('#kpi-balance').textContent=q('#metric-balance')?.textContent||'0.00';q('#infra-road').textContent=`${roads||0} km`;q('#infra-rail').textContent=`${Math.round((roads||0)*.19)} km`;q('#infra-cycle').textContent=`${Math.round((roads||0)*.34)} km`;q('#infra-bridges').textContent=`${Math.max(2,Math.round((roads||0)/18))}개`;q('#env-air').textContent=temp>30?'보통':'좋음';q('#env-runoff').textContent=sim.currentWeather==='rain'?'높음':'낮음'}
function tick(ts){if(!sim._last)sim._last=ts;const dt=Math.min(0.1,(ts-sim._last)/1000);sim._last=ts;if(sim.running){sim.minutes+=dt*sim.speed;if(sim.minutes>=1440){sim.minutes-=1440;sim.date.setDate(sim.date.getDate()+1)}if(ts-sim.lastWeatherChange>18000){sim.lastWeatherChange=ts;updateEnvironment()}else{const hour=sim.minutes/60;if(timeSlider&&Math.abs(Number(timeSlider.value)-hour)>.03){timeSlider.value=hour;timeSlider.dispatchEvent(new Event('input',{bubbles:true}));timeLabel.textContent=formatTime()}q('#env-clock').textContent=formatTime()}}requestAnimationFrame(tick)}
function drawMiniMap(){const c=q('#mini-map-canvas'),ctx=c.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth*dpr,h=c.clientHeight*dpr;c.width=w;c.height=h;ctx.scale(dpr,dpr);const W=c.clientWidth,H=c.clientHeight;ctx.fillStyle='#183036';ctx.fillRect(0,0,W,H);const s=hash(seedInput?.value||'city');ctx.strokeStyle='#376774';ctx.lineWidth=10;ctx.beginPath();for(let y=0;y<H;y+=5){const x=W*.65+Math.sin(y*.07+s*.001)*12;y?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();ctx.strokeStyle='#66787d';ctx.lineWidth=1;for(let i=12;i<W;i+=19){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,H);ctx.stroke()}for(let i=10;i<H;i+=16){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(W,i);ctx.stroke()}ctx.fillStyle='#9fc6d4';ctx.fillRect(W*.43-3,H*.48-3,6,6);ctx.strokeStyle='#dbe9ed';ctx.strokeRect(W*.25,H*.22,W*.42,H*.48)}
function setAnalysis(mode){sim.analysis=mode;const l=q('#analysis-layer');l.className=`analysis-layer ${mode==='none'?'':mode}`;qa('[data-analysis]').forEach(b=>b.classList.toggle('active',b.dataset.analysis===mode))}
function bind(){q('#sim-running').addEventListener('change',e=>sim.running=e.target.checked);q('#sim-speed').addEventListener('change',e=>sim.speed=Number(e.target.value));q('#climate').addEventListener('change',e=>{sim.climate=e.target.value;updateEnvironment()});q('#weather-mode').addEventListener('change',e=>{sim.weather=e.target.value;updateEnvironment()});qa('[data-analysis]').forEach(b=>b.addEventListener('click',()=>setAnalysis(b.dataset.analysis)));q('#layer-collapse').addEventListener('click',()=>q('#layer-panel').classList.toggle('collapsed'));q('#district-focus').addEventListener('change',e=>{q('#district-label').textContent=e.target.options[e.target.selectedIndex].text.toUpperCase();q(`[data-camera="${e.target.value==='cbd'?'center':'overview'}"]`)?.click()});q('#generate')?.addEventListener('click',()=>setTimeout(()=>{sim._seed=hash(seedInput.value);drawMiniMap();updateKPIs()},250));q('#random-seed')?.addEventListener('click',()=>setTimeout(drawMiniMap,100));const observer=new MutationObserver(updateKPIs);qa('.metric-grid dd').forEach(el=>observer.observe(el,{childList:true,characterData:true,subtree:true}));window.addEventListener('resize',drawMiniMap)}
function init(){bind();sim._seed=hash(seedInput?.value||'city');drawMiniMap();updateEnvironment();requestAnimationFrame(tick)}
init()
